Sprint 2
Shurumov/middle.messenger.praktikum.yandex pull request #4
Opened 2022-01-29 19:47 UTC by Shurumov

2022-01-30 20:41 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, все выглядит очень не плохо. Из критичного - только некоторые проблемы с типами (хорошо бы избавиться от any в местах где он точно не нужен). Остальное описал в комментарих)

2022-01-30 20:41 UTC, DmitryKhitrin commented on .eslintignore
> +/node_modules
Для git важно что бы файл заканчивался[ пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-01-30 20:41 UTC, DmitryKhitrin commented on .parcelrc
>  }
[EOF](https://eslint.org/docs/rules/eol-last)

2022-01-30 20:41 UTC, DmitryKhitrin commented on .stylelintrc.json
> +}
EOF

2022-01-30 20:41 UTC, DmitryKhitrin commented on server.js
> +});
На практике, для функций колбеков, обычно используют `() => {}`, стрелочные/лямбда функции)

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/chat-input/chat-input.scss
> +    background-color: #EFEFEF;
Цвета обычно удобно выносить в css переменные, так в будущем будет проще вносить изменения, ведь придется поправить всего один файл, а не сотни)

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/chat-input/chat-input.ts
> +  constructor(props: FormFieldProps & Props) {
1) Лучше вынести `FormFieldProps & Props` в файл с описанием пропсов:

`type FormFieldProps = {a: number, b: string} & Props;`

Такой вариант как будто более логичный;

2) Тип передаваемого значения принято именвовать ComponentName + Props -> ChatInputProps

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/chat-input/chat-input.ts
> +      props.events = props.events ?? {};
Данную проблему стоит решать немного иначе:

props лучше типизировать через [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников.

В общем виде должно получиться, что-то такое:

```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}

```

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/chat-input/chat-input.ts
> +        focus: (event: FocusEvent) => validationMethod(event.target),
Функции обработчики ивентов принято именовать вот так:  `onFocus || handleFocus`

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/form-field/form-field.model.ts
> +  button = "button",
Ключи в [enum](https://www.typescriptlang.org/docs/handbook/enums.html) принято именовать с заглавной буквы, это можно увидеть даже в примерах из документации:

```
enum Cars {
    Bmw = "bmw",
    Lada = "lada",
}
```

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/form-field/form-field.ts
> +import { FormFieldProps } from '~src/components/form-field/form-field.model';
Честно говоря, первый раз вижу, что бы корень проекта указывали через тильду. Обычно это делается через `/src/...`. Если же это корень домашней директории на файловой системе, то так делать тоже не стоит, ведь при переноси папки все импорты могут поехать

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/components/form-field/form-field.ts
> +import { FormFieldProps } from '~src/components/form-field/form-field.model';
+ обычно в проекте выбирают единый стиль записи импортов, мешать абсолютные и относительные - не очень хорошая практика

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/pages/404/index.html
> +</html>
EOF

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/pages/500/index.templ.ts
> +  <div class="error-page__text">Мы уже фиксим</div>
Текст лучше вынести в переменную и передавать снаружи. Зачем? К примеру так будет гораздо удобней завозить в проект новые языки)

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/pages/edit-profile/index.html
> +</html>
EOF

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/pages/profile/index.ts
> +      userInfo: [
Моковые данные обычно выносят в отдельный файл, что бы не загромождать код компонента

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/pages/profile/index.ts
> +// import templateFunction from './index.hbs';
Ненужные комменты стоит удалять из проекта, либо оставлять комментарий с причиной по котором это здесь находится. Память недолговечна и уже через пару недель знания о том что мы здесь имели в виду выветриваются(

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/pages/sign-in/index.html
> +</html>
EOF

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/block/block.ts
> +  setProps = (nextProps: any) => {
Тут не должно быть any, в крайнем случае Object, а лучше generic от Props (в комментарии выше, описал что я имею в виду). В данном случае в это функци кто-нибудь может передать `null` или `undefined` и код упадет. А TS призван уберегать нас именно от проблем этого вида.

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/event-bus/event-bus.ts
> +  listeners: { [key: string]: ((...args: any[]) => void)[] };
Для таких типов есть удобный хелпер [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type):

`Record<String, (...args: any[]) => void>`

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/fetcher/fetcher.ts
> +  request = (url: string, options: OptionsMethod, timeout = 5000) => {
Этот метод стоит сделать [private](https://metanit.com/web/typescript/3.4.php), так как его вызов должен быть только изнутри этого класса. Остальные же методы, как раз должны быть publiс.

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/fetcher/fetcher.ts
> +      if (!method) {
Эта проверка здесь не нужна, так как эту ситуацию должен проверять и разруливать TS. В случае, если кто-то не передаст метод, код просто не скомпилируется.

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/fetcher/fetcher.ts
> +        isGet && !!data
!!data -> Boolean(data) - явное преобразование выглядит нагляднее) А наглядность - очень важный критерий кода)

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/fetcher/fetcher.ts
> +        isGet && !!data
Тут кажется хватит просто проверки на наличие data

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/fetcher/fetcher.ts
> +      if (isGet || !data) {
Тут тоже хватит проверки на наличие поля data

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/send-form-handler/send-form-handler.ts
> +  const form = document.forms[index]
Хорошая практика что бы функция делала что-то одно. В данном случае в названии указано, что функция посылает данные формы, а по факту, она достает форму из хранилища и только потом обрабатывает > передавать в функцию форму снаружи

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/send-form-handler/send-form-handler.ts
> +}
EOF

2022-01-30 20:41 UTC, DmitryKhitrin commented on src/utils/validation/form-validation.ts
> +          (acc: { [key: string]: string | number }, input: HTMLInputElement) => {
```suggestion
          (acc: { [key: string]: string | number }, {name, value}: HTMLInputElement) => {
```

2022-01-30 20:41 UTC, DmitryKhitrin commented on tsconfig.json
> +}
EOF

2022-01-31 10:31 UTC, Shurumov commented
Привет, спасибо за замечания постарался всё исправить

2022-01-31 21:41 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки и удач в следующем спринте!)

2022-01-31 21:41 UTC, DmitryKhitrin commented on src/components/form-field/form-field.ts
> +        focus: handleEvent,
Обычно это все же onFocus, onBlur тут кажется onFocusOrBlur

2022-02-01 13:17 UTC, merged