Sprint 4
Shurumov/middle.messenger.praktikum.yandex pull request #6
Opened 2022-03-13 14:11 UTC by Shurumov

2022-03-13 18:47 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, сборка выглядит отлично, но есть некоторые функциональные проблемы проекта, которые хотелось бы поправить:

- ввод не валидного url приводит к отображению пустой страницы, хотя в этом случае должна отображаться 404;
- ввод не валидных логина или пароля, никак не отображаются в интерфейсе, хотя сервер по честному отдает 401 с сообщением `reason":"Login or password is incorrect"`. В данном случае надо выводить это пользователю иначе это выглядит как зависшая страница, юзер жмет на кнопку и ничего не происходит
- нет обработчиков ошибок на асинхронных операциях, с выключенным интернетом, попытка авторизоваться, бросает в консоль необработанную ошибку, а в идеале, стоит так же выводить в интерфейс уведомление, что приложение не доступно без интернета

давайте попробуем исправить эти проблемы, все же финальный спринт)

2022-03-13 18:47 UTC, DmitryKhitrin commented on .dockerignore
> +node_modules
Для git важно, что бы файл заканчивался [пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-03-13 18:47 UTC, DmitryKhitrin commented on server.js
> +app.get("*", (req, res) => {
Сервер тоже можно написать на typescript, для удобства запуска есть такие утилиты как [ts-node](https://www.npmjs.com/ts-node)

2022-03-13 18:47 UTC, DmitryKhitrin commented on server.js
> +app.listen(process.env.PORT, () => {
Может произойти такая ситуация, что в окружении не окажется переменная PORT, для такого случая, лучше добавить проверку либо значение по умолчанию:

```
const PORT = 3000;
const port  = process.env.PORT || PORT;
```

2022-03-13 18:47 UTC, DmitryKhitrin commented on src/components/users-list/users-list.ts
> +          input: (event: any) => {
У ивента тип не any, а Event

2022-03-13 18:47 UTC, DmitryKhitrin commented on src/utils/block/block.ts
> +        // @ts-ignore
Тут кажется нужна проверка на наличие элемента, а не ts-ignore

2022-03-14 16:29 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки и удачи в следующем спринте)

Дальше только интересней!

2022-03-15 08:31 UTC, Shurumov commented on src/services/auth.service.ts
> +        alert(err?.message)
Спасибо за замечание, про блокирование потока в курсе, просто надо было как-то быстро решить вопрос с уведомлением, поэтому так)

2022-03-15 08:31 UTC, merged